#!/usr/bin/env python3

# rdserialtool
# Copyright (C) 2019-2021 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

if __name__ == '__main__':
    import sys
    import rdserial.tool
    sys.exit(rdserial.tool.main())
